### ISSUE TITLE
cutoff rounding

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-closing#107]
We have had a case of unbalanced bs/pl accounts due to the cutoff module. 

I think it should [apply rounding here](https://github.com/OCA/account-closing/blob/6c0a8956bf6b4b565c8c5c92671661f5093370e5/account_cutoff_accrual_dates/models/account_cutoff.py#L44-L45).

Otherwise we end up with accounting entries with many decimal which cause issues down the line.

@alexis-via what do you think?

**Comment by sbidoul** [comment]
cc/ @chrisdec

**Comment by gaikaz** [comment]
It looks like we encountered this issue as well on Odoo 12.0.
@sbidoul Any more intel on this after a year?
Seems like your mentioned code is still there in v13

**Comment by alexis-via** [comment]
@gaikaz Do you have the proof that the bug still exists in v13 ? The rounding is not done in the cutoff line, but when generating the account.move.line, and this code is in account_cutoff_base, and, for me, the fix is included in v13 (cf calls for round() in account_cutoff_base in v13).

**Comment by gaikaz** [comment]
No, we only just found it on v12.
Today a coworker will try to reproduce this on the Community Runbot with as little configuration as possible. If it works, we'll check it on v13.

In short, I will write here about anything she finds.

**Comment by alexis-via** [comment]
Did you find it on v12 with up-to-date code ? It would be very surprising, because the fix is also present in v12.

**Comment by gaikaz** [comment]
Indeed, our client was still running older code.
We kind of wasted a little time now. I compared the versions and they were the same. Why was the version not bumped on PR merges? I trusted that we have the newest one on the client server :stuck_out_tongue: 

I think this issue can be closed, though.

**Comment by gaikaz** [comment]
@alexis-via 
I thank you for the quick responses 😊
We didn't have any more trouble anymore.
