### ISSUE TITLE
[7.0] various issues on account_multicurrency_revaluation reports

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-closing#11]
- Need to add the possibility to add an analytic account on the P&L account 
  ![image](https://cloud.githubusercontent.com/assets/5735158/6441055/1bbe6b52-c0e4-11e4-804e-838e79458134.png)
- Open Invoice Report : 'Option 'Group by currency' has no effect anymore
- Report 'Print Currency Unrealized' has no template linked

**Comment by fclementic2c** [comment]
Report 'Print Currency Unrealized' has no template linked -> due to complex on set up -> should be improved with https://github.com/OCA/account-closing/pull/15

**Comment by yvaucher** [comment]
closed by #15 
@fclementic2c you confirm ?
