### ISSUE TITLE
account_multicurrency_revaluation is not correct for bank account

### ISSUE THREAD

**Issue by xfx-oscg** [OCA/account-closing#117]
For bank account, partner_id is replaced by False, but amount is not  sumed. 
File account_multicurrency_revaluation\model\account.py , method def compute_revaluations  , code line accounts[account_id][partner_id][currency_id] = line should be replaced by code below :
```
            #accounts[account_id][partner_id][currency_id] = line
            org_line = accounts[account_id][partner_id][currency_id]
            if not org_line:
                line['partner_id'] = partner_id
                accounts[account_id][partner_id][currency_id] = line
            else: 
                org_line['balance'] += line['balance']
                org_line['debit'] += line['debit']
                org_line['credit'] += line['credit']
                org_line['foreign_balance'] += line['foreign_balance']
```

**Comment by alexey-pelykh** [comment]
@xfx-oscg thanks for the suggested fix, will try it out, seems it's addressing https://github.com/OCA/account-closing/issues/126

**Comment by alexey-pelykh** [comment]
See https://github.com/OCA/account-closing/pull/149
