### ISSUE TITLE
[7.0] account_multicurrency_revaluation too much complexity on set up 

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-closing#12]
We think the set-up of this module in the company settings is far too complex and can generate errors in reports.

It has been initially implemented this way in order to be able to automatise the provisioning entry that you must post in some country (ie: France) on top on the revaluation entry.

However, the second entry is not required in all countries and it is really basic (just 2 lines). The really complexity is the calculation of the revaluation er account and  the report showing the details of this calculation.

So I suggest to get rid of the functionnality allowing you to post the provision entry so the user can only fill 2 default account instead of 6 in the company settings.

I propose the following changes: 
- simplifing the view to this one : 
  ![image](https://cloud.githubusercontent.com/assets/5735158/6459027/ad40975c-c18a-11e4-8edc-ce55fb2f65b1.png)
- hide deprecated fields 
  Since we cannot delete fields in v7 we will simply add a check box mecanism th hide the too complex settings but it will remain possible to unhide it thanks to a checkbox in the accounting settings
  note : the idea is to delete these fields + method linked whenever this module will be ported to v8.
- add few comments to help end-users

**Comment by fclementic2c** [comment]
see : https://github.com/OCA/account-closing/pull/15

**Comment by yvaucher** [comment]
closed by #15
