### ISSUE TITLE
Cut-off modules : ideas for v14

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-closing#133]
Working on the migration of the cutoff modules for v13 these last days, I had some thoughts about structural changes that I propose to make when we'll migrate to odoo 14:

1) Integrate account_cutoff_accrual_base in account_cutoff_base

2) Merge account_cutoff_prepaid and account_cutoff_accrual_dates. The name I propose for the merged module would be account_cutoff_start_end_dates.

I think it will make things easier to understand for users.

Please tell me what you think. Feel free to share other ideas that you have for the future.

**Comment by alexis-via** [comment]
First, don't hesitate to give your opinion on this... I plan to start working on it in a few days, so it will soon be too late !

To be able to make this important re-organisation of the account_cutoff_* modules, I plan to port all of them in the same PR. If you think it's a big problem, yell now...

**Comment by pedrobaeza** [comment]
AFAIK, Odoo now includes deferred income/expenses on core since v13. Did you check it?

**Comment by alexis-via** [comment]
It's surprising that it's in Odoo Community. Will be moved to Odoo Enterprise sooner or later...
AFAIK, @fclementic2c from Camptocamp had a look at it, and he prefered using the OCA modules with start/end dates... could you confirm Frederic ?

**Comment by alexis-via** [comment]
Link to issue #142

**Comment by sbidoul** [comment]
@alexis-via I'll need to test `account_cutoff_accrual_dates` to better understand how these fit together, it's new to me. Does it not overlap with `account_invoice_accrual`?

**Comment by alexis-via** [comment]
account_cutoff_accrual_dates uses start/end dates on move lines (so the invoice needs to be confirmed) to compute expense and revenue accruals. This is useful for the following scenario : at the beginning of February, you generate the expense accruals for 31/12 and it will find a posted supplier invoice dated in January that has start/end dates in december.

**Comment by alexis-via** [comment]
FYI, all the ideas written here have been implemented in the v14 migration PRs.

**Comment by alexis-via** [comment]
All the ideas have been implemented in v14, so I close this issue.
