### ISSUE TITLE
Incorrect test

### ISSUE THREAD

**Issue by sergiocorato** [OCA/account-closing#157]
This test won't work in the specific days it force creation of rate without checking they already exists.
https://github.com/OCA/account-closing/blob/99cc993aa06b17df00642dc25f4a8c31fc8f3e20/account_multicurrency_revaluation_rate_type/tests/test_currency_revaluation.py#L33

**Comment by pedrobaeza** [comment]
You can remove in the setup all the existing rates. I did that in other test.

**Comment by sergiocorato** [comment]
Thanks, I'll do it.

**Comment by sergiocorato** [comment]
Not really sure how to replicate bug, without waiting for 1st december
https://github.com/OCA/account-closing/pull/158
