### ISSUE TITLE
V11 unaligned wrt v10 and v12

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/account-closing#164]
Hello everyone,
we've noticed that most modules from v11 are not aligned to their v10 and v12 counterparts.
More accurately, it seems that updates that were introduced in v10 and then ported to v12 via #112 are totally missing from v11, where many modules seem untouched from the day they were migrated (not considering translations, I mean).

Is there a reason behind this? Or is it because v11 is quite unused, so noone took care to keep it updated and aligned to v10 and v12?

I'm asking because we'd need to use some modules that our customers already use (v12), but we'd need them to be installable on v11. So we installed them (v11 of course, not v12), but a few features seemed missing (for example, button "Re-Generate Lines" in [`account.cutoff` form view](https://github.com/OCA/account-closing/blob/11.0/account_cutoff_base/views/account_cutoff.xml#L23)), so we noticed that the reason behind it was the aforementioned unalignment.

So, before opening a PR to align the code on v11 from v12, I would like to know whether it was a deliberate choice, because (if it was) it wouldn't be worth the effort :sweat_smile:

**Comment by sergiocorato** [comment]
AFAIK, the 11.0 port is unused, see abandoned https://github.com/OCA/account-closing/pull/146
