### ISSUE TITLE
[multi_currency_revaluation] - Partially wrong revaluation result (only at one account it is wrong, while others account are correct)

### ISSUE THREAD

**Issue by bunhin** [OCA/account-closing#167]
Have some currencies activated and used base currency IDR, other foreighn currency USD and JPY. Some accounts including payable and receivable accounts, and liquidity account (banks and cashes account are allowed for revaluation.
When the revaluation is done,  all revaluation for banks and cashes, and payables are OK, but a receivable account is got incorrect entry.

Situation:

currency rate is entered one time of every month end revaluated  with currency entered at the end of the month.

On the error revaluated account:
There are transaction (register payment to a customer invoice at USD --reconciled, using bank at USD currency) at the end of the month (31th March 2021)
The bank statements are entered at 6th of April 2021 with date in statment lines 31 March 2021, they are all reconciled
Entered a currency rate at 31 March 2021
Do currency revaluation with date = 31 March 2021

Result:
The revaluation entry on the USD Bank was correct
The revaluation entry at the account receivanle was not correct (It seem that the registered payment at 31 March 2021 not counted on the balance of the account receivable)

Try to read the code, i suspect that the transaction of 31 March 2021 is not included in the revaluation  because   "date < %" in the query to fetch the move lines.

Expected:
The registered payment on 31 March 2021 should deduct the balance of receivable and the unrealize exchange diff to be correct.

**Comment by hailangvn** [comment]
Good day Bun,
Thanks for reporting the issue. We tried below steps to reproduce but found no issue. Could you please verify the steps and advise what are differences with your steps and expectation? Why do you expect that?

```
Step 0: setup
    * Company currency: JPY
    * No exchange difference journal, gain/loss accounts
    * Revaluation accounts: XR001 Reval Loss + XR002 Reval Gain
    * Provision B.S accounts: None
    * Provision P&L accounts: None
Step 1: create invoice with USD currency on 31-Mar-2021
    Journal Entry           Account                 Matching    Debit       Credit      Balance
    SJ/2021/03/0001         Receivable              A21           100            0          100
    SJ/2021/03/0001         Revenue                                 0          100         -100
Remark: As no currency rate is entered, rate 1.0 is used.
Step 2: create payment from the invoice on same day
    Journal Entry           Account                 Matching    Debit       Credit      Balance
    BJ US/2021/03/0001      Liquidity USD                         100            0          100
    BJ US/2021/03/0001      Receivable              A21             0          100         -100
Step 3: create USD bank statement on 06-Apr-2021 with line on 31-Mar-2021
    Journal Entry           Account                 Matching    Debit       Credit      Balance
    BJ US/2021/03/0002      Bank Journal USD                      100            0          100
    BJ US/2021/03/0002      Suspense                                0          100         -100
Step 4: reconcile
    Journal Entry           Account                 Matching    Debit       Credit      Balance
    BJ US/2021/03/0002      Suspense -> Liquidity USD               0          100         -100
Step 5: create USD currency rate 0.75 on 31-Mar-2021
Step 6: run wizard to revaluate for 31-Mar-2021
    Journal Entry           Account                 Matching    Debit       Credit      Balance
    RJ/2021/03/0002         Bank Journal USD                    33.33            0        33.33
    RJ/2021/03/0002         Reval Gain                              0        33.33       -33.33
Remark: USD/JPY = 0.75 --> 100 USD = 100 / 0.75 JPY ~ 133.33 JPY --> gain 33.33 JPY
```

**Comment by bunhin** [comment]
Hai @hailangvn,
I am still looking my side. But maybe i still miss or not understanding the revaluation concept of the addon. But i find this 2 case:

1. If there is no reconciliation made, although there are many account with currency amount balance, when i do the revaluation, no revaluation journal is generated.

2. I have 2 bank account in foreign currency  (differ from company currency) eg company (base ) currency in IDR, while have bank account in USD and JPY, and have two internal transfer during the month from USD to JPY Bank, both already reconciled, and i see the journal is correct including the exchange rate journal generated.

When I do the currency revaluation this 2 banks USD and JPY --> have revaluation journal with not correct amount.

So I have these question:
1.  if  we have bank account from opening entry  at ending of a month said in USD 2000  while the Base Cureency in IDR  with currency rate X at the opening entry date, then simulate no other transaction until the end of the next month, end at then of the month we entry new rate = Y.   With this only one transaction (opening entry) should the module generate revaluation amount 2000 * (Y-X)?   --> if in real the value of that bank in base currency should already have unrealized exchange difference.

2. Or if said we only have one invoice in USD (base currency in IDR for example), until end of the month the invoice in not paid at all, and at the end of the month the usd rate already differ from the rate at date of invoice is posted. Will the module generate revaluation entry? Should it?

3. If we do internal transfer  from foreign bank to foreign bank --> the amount currency field  and the foreign currency is differ from the bank currency (if transfer from usd bank to jpy bank and the transfer in usd currency, in  jpy bank will have amount currency in USD while ammount in JPY  (this is in the bank statement line), have this module correctly consider this?
