### ISSUE TITLE
[12.0] account_fiscal_year_closing

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-closing#175]
@pedrobaeza This accounting closure is compatible with the OCA sys and MIS builder? Since it is understood that the OCA sys and MIS builder calculate the 129 in real time, and that if the closure is used the data in the OCA sys and MIS builder reports, the data of the 129 would be duplicated.

Currently all the agencies and consultancies request the printing of the annual accounting journals (they even request it because they say it is by law) including the opening and closing, so currently you have to be getting a sys as of 12/31 of the previous year by pasting in the excel as entry nº1, then renumber from entry nº2 and then the sys as of 12/31 of the closed year and paste in the excel as closing entry, I believe that this is not a very suitable procedure for an accounting closing.

It is right? Is closure going to be implemented from now on?

**Comment by pedrobaeza** [comment]
No, it isn't. You shouldn't install this module in Spain.
