### ISSUE TITLE
account_cutoff_start_end_dates has missing migrations

### ISSUE THREAD

**Issue by lorenzoallegrucci** [OCA/account-closing#238]
## Module
account_cutoff_start_end_dates

## Describe the bug
    cutoff_days = fields.Integer(
        readonly=True,
        help="In regular mode, this is the number of days after the "
        "cut-off date. In forecast mode, this is the number of days "
        "between the start date and the end date.",
    )  # Old name: prepaid_days

The above field needs to be migrated,

and the below field from https://github.com/OCA/account-closing/blob/11.0/account_cutoff_prepaid/models/account_cutoff.py#L179

is missing in the new module:

```
    move_line_id = fields.Many2one(
        'account.move.line', string='Account Move Line', readonly=True)
```
 maybe this field should be migrated too?

## To Reproduce
**Affected versions**: 14.0

**Expected behavior**
old data in `prepaid_days` must be migrated in `cutoff_days` and maybe `move_line_id` too

**Comment by sergiocorato** [comment]
Migration of `prepaid_days` is done from 2021: https://github.com/OCA/account-closing/blob/97a40eac47911be0de1938978304bf1a23eb8237/account_cutoff_start_end_dates/hooks.py#L31
`move_line_id` is no more used.
