### ISSUE TITLE
[15.0] account_cutoff_start_end_dates tax_ids is not set on cut-off account move

### ISSUE THREAD

**Issue by tv-openbig** [OCA/account-closing#262]
If you create a new cut-off type "accrued revenue" at a certain cut-off date in order to move the income and the taxes to prior period the field "tax_ids" from the origin move is empty. This will lead to wrong tax reports in the period of the cut-off.

## Module
account_cutoff_start_end_dates

## Describe the bug
The cut-off moves will be created but the tax_ids and therefore the tax_tag_ids on the lines will miss.

**Affected versions**:
at least 15.0

## To Reproduce
Configure the accounts in the settings (check module configuration advises)
Create a invoice with the date "2023-02-10"
Enter a line with start date "2023-01-01" and end date "2023-01-31"
Enter also a sale tax on the line (with configured "tag_ids").
Go to Accounting > Accounting > Cut-Offs > Accrued Revenues
Click on "Create"
Enter the cut-off date "2023-01-31".
Click on re-generate lines.
Click on "Create Journal Entry"
Check the move lines with the income account (cut-off value) and the tax account.
The tax on the line of the deferred revenue account is missing (also tax grid).

**Expected behavior**
The tax should be on the lines of the cut off account move lines.

**Additional context**
Video:
https://drive.google.com/file/d/1tSjaz6J86ZtLiUL9dtJSCnOyvaHPjEXB/view

**Comment by sergiocorato** [comment]
At least in Italy VAT is computed by date of the event and is not moved to date of competence.
Other taxes on competence are computed in more specific ways.
