### ISSUE TITLE
Currency Revaluation Incorrect Journal Entries

### ISSUE THREAD

**Issue by ztsiklauri** [OCA/account-closing#28]
I don't understand the logic of journal entries of currency Revaluation Module. As I understand, it should find the amounts held in different currency and make adjustment journal entry like: If my base currency is USD and I had 1000 EUR Cash and rate was 1EUR=1.3USD, and now rate went to 1.1 USD, when I use the option of revaluation in this module, it should credit the cash account by 200 and debit the Loss account(configured in company settings as needed) with 200.  So that I will have a real picture on my ledger as before my balance was 1300, now it will be 1100 USD. Instead of this, this module makes the journal entry with total amounts, and closes my currency account. Is it revaluation or period closing of an account?

**Comment by elicoidal** [comment]
AS far as I know the module creates one final move for all differences. 
This is not wrong but it is confusing for the accountant I have spoken to.
One nice improvement of the module could be to have the possibility to 
have details when generating the accounting entry.
Eric CAUDAL

**Comment by fclementic2c** [comment]
Try maybe to check/uncheck in the account form 'allow revaluation'

**Comment by ztsiklauri** [comment]
I mean its not a revaluation, its closing the balance. I was hoping would revalue my foreign currency, update the balances I see in base currency and make gain or loss journal entries depending on the exchange rate fluctuations over time. 

I suggest to improve this module and make real currency revaluation, not the closing journal entries.

**Comment by fclementic2c** [comment]
well...It is the case... but set up is not easy I agree ; check the read me
