### ISSUE TITLE
Bug in Fiscal Year Closing module in odoo version 14

### ISSUE THREAD

**Issue by Evaguadaltech** [OCA/account-closing#280]
![error-cierre-ejercicio-comufri](https://github.com/OCA/account-closing/assets/122524105/d378bd94-f372-4da4-8904-334a16841e7d)
Hello, when we have created a year-end closing and we have added the transaction configuration. When saving or calculating the year-end closing it gives the attached error. And it does not create the year-end closing.

Thank you.

**Comment by DesarrolloWIL** [comment]
I have the same problem, I am investigating the origin of it.

**Comment by Evaguadaltech** [comment]
Buenos días, ¿se ha podido corregir a dia de hoy la incidencia que he indicado en odoo 14?

Gracias.

**Comment by mide-dynapps** [comment]
Hi, same issue.
I thinks it's linked to PR https://github.com/OCA/account-closing/pull/199 for the migration into v14

Any chances to revert commit https://github.com/OCA/account-closing/commit/fb4c3ee760231b066f4085984e8abcbf8f4b2b56 ?
I don't understand the need for this code :)
And w/o this code, it seems to work fine.

**Comment by mide-dynapps** [comment]
**How to reproduce:**
- settings => for current user, set checkbox on user profile 'Show Accounting Features - Readonly'
![image](https://github.com/OCA/account-closing/assets/79934758/cfedb9a8-63a3-421b-9b9b-f88086152da4)

- Invoicing / Accounting / Fiscal year closing => create new entry:
![image](https://github.com/OCA/account-closing/assets/79934758/29a8bef8-dd73-4f2d-b2bd-32591195ee8a)
![image](https://github.com/OCA/account-closing/assets/79934758/2d99fff1-8e43-4348-a047-0e9ca80d1c0c)

**Result:** Impossible to Save or Calculate => crash with traceback

**Comment by Evaguadaltech** [comment]
Hola, el error lo daba cuando el campo Destination account lo pongo vacio cuando el campo Move type es Closing. ¿me habeis entendido?

Gracias.
Un saludo.

**Comment by mide-dynapps** [comment]
@Evaguadaltech any chance to test the PR #294 ?

**Comment by Evaguadaltech** [comment]
Hola, los cambios que has indicado los he probado en local y me han funcionando correctamente. 

Gracias. 
Un saludo.
