### ISSUE TITLE
Multicurrency revaluation installation removed COA template

### ISSUE THREAD

**Issue by jpcass** [OCA/account-closing#56]
Hi, after installing, Multicurrency revaluation (v10) the chart of accounts template configured was removed from the corresponding field in the accounting settings, is this an expected result? Thanks

![image](https://user-images.githubusercontent.com/29762062/32135473-2a03e3b4-bbd6-11e7-9229-4fd5c7f03f52.png)

**Comment by grindtildeath** [comment]
@jpcass Sorry I only see your issue now, but IIRC this behaviour was due to the onchange which was fixed through this commit : https://github.com/OCA/account-closing/commit/4ba526c06bde1b5df98d9ecf752276394cf07f2d

Can you please confirm ?
