### ISSUE TITLE
account_currency_revaluation wrong computation of xrate difference

### ISSUE THREAD

**Issue by hbto** [OCA/account-closing#87]
After running wizard for Revaluation on Receivable Account and adding new journal entries
the wizard does not compute properly the xrate difference.
In this video this can be observed.

https://youtu.be/FHpR4jO03-4

Regards.

**Comment by goliveirab** [comment]
@hbto 

Could you please check if this issue es fixed... 

The fix is here https://github.com/Vauxoo/account-closing/pull/2
and you can test it here: http://3349352-88-fcf6e0.runbot1.odoo-community.org

Regards

**Comment by goliveirab** [comment]
@hbto 

Here is a video testing the fix with the same flow as the one you posted before...
https://drive.google.com/file/d/1NrR0f-LGX1L0doXZXtOWnEJfqDkA3VcJ/view
