### ISSUE TITLE
Error in creating databases with demo data

### ISSUE THREAD

**Issue by labaggio** [OCA/account-closing#94]
The odoo account module, in Payment methods, already inserts a record with id account_payment_method_manual_in:
https://github.com/odoo/odoo/blob/fe381f95b704085eb16b23ed74da7924ae0872e7/addons/account/data/account_data.xml#L85

 You are trying to insert a record with the same id, conflicting with the former.

https://github.com/OCA/account-closing/blob/fb78e8a2b84a7fd38d9883b039613aa6dd9af0f8/account_multicurrency_revaluation/demo/account_demo.xml#L128

**Comment by pedrobaeza** [comment]
The XML-ID is composed by the module name + the id, so no collapse. Any specific problem apart from observing the same id?

**Comment by labaggio** [comment]
When I try to install this module into  a database  with  "Load demonstration data" checked, I have this error:
![schermata del 2018-12-29 16-02-14](https://user-images.githubusercontent.com/25666721/50539585-26bc3280-0b83-11e9-81f7-9f7234a0928f.png)
I'm doing other tests because it does not happen if I install the single module..

**Comment by pedrobaeza** [comment]
Fixed in #95
